apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-map-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: map-server
  template:
    metadata:
      labels:
        app: map-server
    spec:
      containers:
      - name: nginx
        image: nginx:latest # מדמה את ה-MapServer
        resources:
          requests:
            cpu: "100m" # הגדרת משאבים קריטית ל-Autoscaling
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        ports:
        - containerPort: 80
---
# זה החלק שיוצר את ה-Load Balancer של אמזון אוטומטית!
apiVersion: v1
kind: Service
metadata:
  name: public-map-service
spec:
  type: LoadBalancer 
  selector:
    app: map-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# בונוס Autoscaling (HPA)
# אם ה-CPU של הפודים עובר 50%, הקלאסטר ייצר עוד פודים
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: map-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: public-map-server
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50